if [[ "$(uname)" =~ CYGWIN_NT ]]; then
    alias gith='/usr/bin/git -c user.name="jensgustafsson" -c user.email="jensgustafsson89@gmail.com"'
    alias ipy='winpty.exe ipython3'
    alias rednose='winpty.exe nosetests --rednose --force-color'
    alias mynet='netstat -a -n -o'
    alias open='cygstart'
    alias sudo='cygstart --action=runas'
    alias cmd='cygstart --action=runas ~/bin/start_cmd.bat'
    alias freeze_it='pip freeze | sed 's/^M$//' >'
    alias mkvenv='deactivate; rm -r venv; wpython3 -m virtualenv venv; av'
    alias lf='winpty.exe limefu'
    alias killall='taskkill /F /T /IM'
    alias wkill='taskkill /F /pid'
    alias code='cygstart code'
    alias wpython3='winpty.exe /cygdrive/c/Python34/python'
    alias wpy='winpty.exe /cygdrive/c/Python34/python'
    alias wmanage='winpty.exe python manage.py'
    alias wman='winpty.exe python manage.py'
fi
